### ISSUE TITLE
Lovelace custom card

### ISSUE THREAD

**Issue by penx** [rccoleman/lamarzocco#16]
Build a custom card that displays the available data, such as provided by aarlo.

Please respond to this ticket with which data would be useful, which data you think may be best ignored, and any screenshots of other cards you like that could be used as inspiration.

**Comment by rccoleman** [comment]
Thanks for opening this!  I don't know what sort of functional differences there are between the GS/3 and Linea Mini, but I was thinking about a card modeled after the Weather Card.

<img width="444" alt="Screen Shot 2021-01-02 at 3 55 02 PM" src="https://user-images.githubusercontent.com/860888/103469059-f92b9600-4d14-11eb-8f90-3f305b4f1a17.png">

Maybe something like this:

Picture/Machine Name         Current coffee temp  Current steam temp
                                               Coffee Set Temp         Steam Set Temp
Auto on/off times
Sun            Mon          Tue            Wed           Thu            Fri            Sat
6a-5pm     6a-5pm    6a-5pm    6a-5pm     6a-5pm     6a-5pm   6a-5pm

**Comment by rccoleman** [comment]
Getting there:

<img width="502" alt="Screen Shot 2021-01-18 at 11 03 55 AM" src="https://user-images.githubusercontent.com/860888/104954372-f9669b00-597c-11eb-9199-2f28fc3838c4.png">

**Comment by rccoleman** [comment]
Okay, I think I'm nearly done.  Here's a view that encompasses the front-panel display, machine power, coffee/steam temps, auto on/off times + enable/disable, and prebrew times + enable/disable.

<img width="938" alt="Screen Shot 2021-01-24 at 11 37 48 AM" src="https://user-images.githubusercontent.com/860888/105641440-d6cef900-5e38-11eb-8758-3325766de66e.png">

Everything works, and the number of prebrew keys adjusts based on the model.  Each of the new card configs look like this:

```
            - type: 'custom:value-range-card'
              entity: switch.buzz_auto_on_off
              card_type: auto
              layout:
                embedded: true
              hide:
                name: true
```
`card_type:` can be `auto` for auto on/off or `prebrew` for prebrew.

I'm getting more comfortable with the Javascript and class structure, but the CSS is still a little mysterious to me.  There's still some leftover stuff from the original time-picker card that I don't fully understand.  Now that the rest is working, I'll poke around with that.

**Comment by rccoleman** [comment]
I just updated everything and added HACS support for the card, so anyone should be able to do the following:

* Update to v0.7.4 of the integration and restart HA
* Add https://github.com/rccoleman/lovelace-value-range-card as a custom HACS repo in the Lovelace category of HACS.
  * Hit the 3 dots in the upper-right corner
  * Choose "Custom Repositories"
  * URL: https://github.com/rccoleman/lovelace-value-range-card
  * Category: Lovelace
* Install the card
* Navigate to Configuration->Lovelace Dashboards->Resources in Home Assistant and see if HACS added a resource with location `/hacsfiles/lovelace-value-range-card/value-range-card.js`.  If not, hit the "+ Add Resource" button in the bottom right and fill out the form:
  * url: `/hacsfiles/lovelace-value-range-card/value-range-card.js`
  * type: `module`
* Add the card to your Lovelace configuration, either via the UI by editing the YAML to add a custom card, or in `ui-lovelace.yaml` if you're managing Lovelace manually.
  * Example:
```
            - type: 'custom:value-range-card'
              entity: switch.buzz_prebrew
              card_type: prebrew
              layout:
                embedded: true
              hide:
                name: true
```

**Comment by rccoleman** [comment]
Added support for viewing/reporting the dose settings on the GS3 AV in the latest card version.

![Uploading Screen Shot 2021-01-29 at 9.30.28 AM.png…]()

```
            - type: 'custom:lamarzocco-config-card'
              entity: switch.buzz_main
              card_type: dose
              layout:
                embedded: true
              hide:
                name: true
```

Note the new `card_type: dose` option.
