### ISSUE TITLE
Linea Mini Water Boiler History Graph

### ISSUE THREAD

**Issue by bpinney** [rccoleman/lamarzocco#22]
The Linea Mini water heater entity graphs the history of the "Temperature" attribute, the setting the user controls, and records in the log book changes to the "State", the current temperature reading of the boiler.

<img width="375" alt="Screen Shot 2021-06-30 at 10 16 43" src="https://user-images.githubusercontent.com/2642102/123977204-ca713e00-d98c-11eb-890d-381f0deee593.png">

I think a more useful representation of the data would be to reversing this to:
  - graph the current temperature fluctuations of the "State" and 
  - record changes of the "Temperature" setting in the log book

**Comment by orxelm** [comment]
Same here.

@rccoleman is there a way to add the current reading entitiy ? I would like to add it to the dashboard.
(I mean not the target temp, but the actual temp reading)

**Comment by bpinney** [comment]
You can use a template sensor for your dashboard. I use this one:

```yaml
  - name: "Linea Mini Boiler Temperature"
    unique_id: "linea_mini_boiler_temperature"
    state_class: measurement
    unit_of_measurement: "°F"
    state: >-
      {{states('water_heater.linea_mini_coffee') | float(0) | round(1) | string | regex_replace(find='\\.0$', replace='') }}
```
