### ISSUE TITLE
Do you want me to add GitHub actions?

### ISSUE THREAD

**Issue by KTibow** [rccoleman/lamarzocco#8]
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by rccoleman** [comment]
Sure, I'm open to contributions.  I've been using PyLint/Black in VSCode for local formatting, but it would be nice if it were enforced in the commit process.  Could you help me understand the packaged/independent distinction?

**Comment by KTibow** [comment]
If it's packaged, then it uses my own repo, ha-blueprint. It contains a reference like this:
```
      - uses: KTibow/ha-blueprint@stable
        name: CI
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
It contains Python, YAML, and sh files. If it's independent, then it all goes in a YAML file inside of your repository. I won't get around to updating it, if I do change it though.
